In [26]:
import numpy as np

###### Python Lists: can hold different data types

In [27]:
things = [1,"sachin",2,3,4,90.8]
print(type(things[-1])) # Reverse indexing
print(type(things[-2]))
print(type(things[1]))
print(things)

<class 'float'>
<class 'int'>
<class 'str'>
[1, 'sachin', 2, 3, 4, 90.8]


###### Numpy arrays: can store only one type of data or object, if input is multiple data type then it will get converted into one with preference of str > float > int

In [28]:
onedim = np.array([1, 1, 2.0, "sachin"])
print(type(onedim[-1])) # Reverse indexing
print(type(onedim[1]))
print(onedim)

<class 'numpy.str_'>
<class 'numpy.str_'>
['1' '1' '2.0' 'sachin']


In [93]:
# arange function:
np.arange(5,10,2) # start, end, step

array([5, 7, 9])

In [104]:
ap = np.array([1,2,3])
for i in np.arange(2):
    ap = np.append(ap,6)
print(ap)


[1 2 3 6 6]


###### Multidimensional array:

In [29]:
multidim = np.array([[1,2,2],[1,2,5]])
print(multidim)

[[1 2 2]
 [1 2 5]]


###### Dimension and shape of array:

In [30]:
print(onedim.ndim)
print(onedim.shape)
print(multidim.ndim)
print(multidim.shape) #returns a tuple
print(multidim.shape[1])

1
(4,)
2
(2, 3)
3


###### Note: when a numpy array is one dimensional, the shape output will be of the form "(x,)" instead of "(x)" inorder to avoid confusion with an integer in parantheses. So it basically distinguishes between a one-element tuple from a paranthesized number.

###### To get the type of array:

In [31]:
print(multidim.dtype)
print(type(multidim))
print(type(multidim[1][0]))

int32
<class 'numpy.ndarray'>
<class 'numpy.int32'>


###### Thing to avoid: Mismatching axis dimensions in multidimensional arrays

In [32]:
multidim_avoid = np.array([[1,2],[1,2,5]])
print(multidim_avoid)

[list([1, 2]) list([1, 2, 5])]


C:\Users\HARSH\AppData\Local\Temp/ipykernel_13408/1777343153.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  multidim_avoid = np.array([[1,2],[1,2,5]])


In [33]:
multidim_avoid = np.array([[1,2],[1,2,5]], dtype='object')
print(multidim_avoid) # numpy array of lists. This is bad cause now it has lost it's speed since it no longer is fully a numpy array.

[list([1, 2]) list([1, 2, 5])]


###### overiding default type: overiding the default type in numpy (int32 and float64); do this to optimize your memory utilization

In [34]:
multidim_overide = np.array([1,2.8,3], dtype = 'int8') #you can also use int16,32,64 or float16,32,64
print(multidim_overide[1])
print(multidim_overide.dtype)

2
int8


###### changing type of an array:


In [35]:
w = np.array([1,2,3,4], dtype = 'int64')
print(w.dtype)
w = w.astype('int8')
print(w.dtype,'\n')

int64
int8 



###### get size of one element of numpy array:


In [37]:
print(multidim.itemsize) # int64 takes 4 bytes of space
print(multidim_overide.itemsize) # int8 takes 1 byte of space

4
1


###### get total number of elements or length of numpy array:

In [38]:
print(multidim.size)
print(multidim_overide.size)

6
3


###### get total size of numpy array:


In [39]:
print(multidim.size * multidim.itemsize)
print(multidim.nbytes) #another way
print(multidim_overide.size * multidim_overide.itemsize)
print(multidim_overide.nbytes)

24
24
3
3


###### Accessing/changing specific elements, rows, cols, etc:


In [41]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[1,2,3,4,5,6,7]], dtype = 'int32')
print("a =", a)
# to get a specific element:
# notation is [r,c]
print(a[1,2])  #exclusive way for numpy arrays only
print(a[1][2]) #can also be done like this traditional lists and c/c++ array way
print(a[0,-2])
print(a[0][-2])

a = [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [ 1  2  3  4  5  6  7]]
10
10
6
6


###### to get a specific row or col:

In [42]:
print(a[1, :]) # first row, every column elements
print(a[:, 6]) # every row elements, sixth column
print(a[1]) #you can get a specific row this way but cannot get a specific col this way

[ 8  9 10 11 12 13 14]
[ 7 14  7]
[ 8  9 10 11 12 13 14]


###### another way to access elements of your choice:

In [43]:
# [starting index(INCLUDED) : ending index(EXCLUDED) : stepsize] and you can also use negative indexing
# if nothing is metioned then by default starting index = 0, ending index = -1(but included), step size = 1
print(a[0, 1:5:1]) #we are talking about 0th index row 
print(a[0:3:1, 3]) #we are talking about 3rd index col
 

[2 3 4 5]
[ 4 11  4]


###### overiding elements:


In [44]:
a[1,2] = 50
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 50 11 12 13 14]
 [ 1  2  3  4  5  6  7]]


###### overiding rows and cols:

In [45]:
a[0, :] = 5 # numpy will broadcast it
print(a)
a[0, :] = [10,20,30,40,50,60,70]
print(a)
a[:, 2] = [99,88,77] #or just mention that single value you want all to have
print(a)

[[ 5  5  5  5  5  5  5]
 [ 8  9 50 11 12 13 14]
 [ 1  2  3  4  5  6  7]]
[[10 20 30 40 50 60 70]
 [ 8  9 50 11 12 13 14]
 [ 1  2  3  4  5  6  7]]
[[10 20 99 40 50 60 70]
 [ 8  9 88 11 12 13 14]
 [ 1  2 77  4  5  6  7]]


###### 3D numpy arrays: you can scale to even higher dimensions

In [46]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
#go from outside in 
print(b[1,0,1]) # like [channel,row/height,col/width]
print(b[1][0][1])
print(b[:, 1, :]) # takes all channels, only first index row, and takes all cols


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
6
6
[[3 4]
 [7 8]]


###### overiding rows and cols of 3D array:


In [51]:
b[:, 0, :] = [[10,11],[12,13]] # The dimension should be same or broadcastable else it will throw an error.
print(b)

[[[10 11]
  [ 3  4]]

 [[12 13]
  [ 7  8]]]


###### initializing different types of numpy arrays:

In [52]:
c = np.zeros((2,3), dtype = 'int16') #makes 2D array of 2*3 dimension containing zeros
print(c)
d = np.ones((3,2), dtype = 'int16')
print(d)
e = np.full((2,3), 101, dtype = 'float32')
print(e)
#to get shape from some other predefined array:
f = np.full(a.shape, 97) #notice we are passing a tuple using a.shape 
print(f)
# or you can use full_like
g = np.full_like(a, 95)
print(g)
print(np.identity(2)) # creating an identity matrix of 2x2 dimension

[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]
[[101. 101. 101.]
 [101. 101. 101.]]
[[97 97 97 97 97 97 97]
 [97 97 97 97 97 97 97]
 [97 97 97 97 97 97 97]]
[[95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95]
 [95 95 95 95 95 95 95]]
[[1. 0.]
 [0. 1.]]


###### random decimal numbers in interval [0,1):

In [53]:
h = np.random.rand(4,3) #Random elements from uniform distribution over [0,1). Also, notice here we are not passing a tuple as the dimension
print(h)
print(np.random.rand()) #to get one random number
# Replace rand with randn to get random elements from standard normal distribution

# .random_sample also generates random numbers from uniform distribution over [0,1), only difference is that it takes in tuple as input
i = np.random.random_sample() #to get one random number 
print(i)
j = np.random.random_sample(a.shape) #this one takes a tuple as input
print(j)

[[0.71607284 0.32787931 0.11653373]
 [0.28668915 0.26216848 0.79313504]
 [0.51096455 0.05007316 0.28828875]
 [0.09627335 0.77480001 0.69451196]]
0.4131935610647198
0.7730170120688783
[[0.64525373 0.95737534 0.44615324 0.60530578 0.36640065 0.06062484
  0.22549843]
 [0.21087313 0.35028755 0.89034863 0.50055079 0.6375039  0.2894597
  0.56309906]
 [0.00644295 0.87286708 0.37506229 0.09951922 0.17997101 0.93300333
  0.58175496]]


###### random integers:

In [54]:
print(np.random.randint(3,9, size = (2,3), dtype = 'int64')) # int in interval [3,9)

[[4 8 8]
 [4 3 8]]


###### Repeat an array:

In [55]:
k = np.array([1,2,3])
print(np.repeat(k, 2, axis = 0)) #only one possible axis i.e. alongside column, so axis = 0 for cols in this case

[1 1 2 2 3 3]


In [56]:
k = np.array([[1,2,3],[4,5,6]])
#two possible axis this time, i.e. axis = 0 for rows and axis = 1 for cols
print(np.repeat(k, 2, axis = 0)) 
print(np.repeat(k, 2, axis = 1))


[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]
[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [57]:
k = np.array([[[1,2,3],[4,5,6]]])
#three possible axis i.e. axis = 0 for channels and so on
print(np.repeat(k, 2, axis = 0),"\n")
print(np.repeat(k, 2, axis = 1),"\n")
print(np.repeat(k, 2, axis = 2),"\n")

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 

[[[1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]]] 

[[[1 1 2 2 3 3]
  [4 4 5 5 6 6]]] 



###### BE CAREFUL WHILE COPYING NUMPY ARRAYS

In [60]:
m = np.array([1,2,3])
n = m
n[1] = 5
print(n)
print(m)
# BOTH CHANGED! EVEN THOUGH WE ONLY CHANGED N. THIS IS BECAUSE WHEN WE DO THIS, BOTH OF THE ARRYAS POINTS TO THE SAME VALUE
# USE COPY METHOD TO PREVENT THIS FROM HAPPENING 


[1 5 3]
[1 5 3]


In [61]:
m = np.array([1,2,3])
n = m.copy()
n[1] = 7
print(n)
print(m)

[1 7 3]
[1 2 3]


###### Mathematics in numpy:

In [63]:
#element wise scalar arithmetic
r = np.array([1,2,3,4])
print(r+2)
print(r-2)
print(r*2)
print(r/2)
print(r**2)
s = np.array([[1,2],[3,4]])
print(s*2)
#element wise tensor arithmetic
s = np.array([4,3,2,1])
print(r+s)
print(np.sin(r)) #similarly for np.cos(r)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[[2 4]
 [6 8]]
[5 5 5 5]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


###### linear algebra:

In [70]:
t = np.ones((2,3))
print(t,"\n")
u = np.full((3,2),2)
print(u,"\n")
v = np.matmul(t,u)
print(v,"\n")
print(np.linalg.det(v), "\n") # determinant
print(u.T) # matrix transpose

[[1. 1. 1.]
 [1. 1. 1.]] 

[[2 2]
 [2 2]
 [2 2]] 

[[6. 6.]
 [6. 6.]] 

0.0 

[[2 2 2]
 [2 2 2]]


###### statistics:

In [72]:
stats = np.array([[1,2,6],[4,5,3]])
print(np.min(stats), "\n")
print(np.max(stats), "\n")
print(np.min(stats, axis = 0), "\n") # for a particular col, compares the rows
print(np.min(stats, axis = 1), "\n") # for a particular row, compares the cols
print(np.sum(stats),"\n")
print(np.sum(stats, axis = 0),"\n") # for a particular col, adds the rows
print(np.sum(stats, axis = 1)) # for a particular row, adds the cols

1 

6 

[1 2 3] 

[1 3] 

21 

[5 7 9] 

[ 9 12]


###### reorganising arrays:

In [75]:
before = np.array([[1,2,3,4],[5,6,7,8]]) # 2x4 = 8
print(before)

# The total number of elements in input to reshape function must be equal to the number of elements in the before array.
after = before.reshape((8,1)) # 8x1 = 8
print(after)
after = before.reshape((4,2)) # 4x2 = 8
print(after)
after = before.reshape((2,2,2)) # 2x2x2 = 8
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###### vertically and horizontally stacking vectors:

In [76]:
# basically similar to concatination or appending
# vertical stacking
v1 = np.array([[1,2,3,4],[4,3,2,1]])
v2 = np.array([5,6,7,8])
print(np.vstack((v2,v1,v2))) #the number of cols must be same but number of rows can be different! so we can stack a vector with a matrix!


[[5 6 7 8]
 [1 2 3 4]
 [4 3 2 1]
 [5 6 7 8]]


In [78]:
# horizontal stacking
# number of rows should be same but number of columns can be different

h1 = np.zeros((3,2))
print(h1, '\n')
h2 = np.ones((3,5))
print(h2, '\n')
print(np.hstack((h1,h2)),'\n')  #[h1,h2] will also work, and so is [v2,v1,v2]


[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]] 



###### load data from a file:

In [79]:
output = np.genfromtxt(r'E:\academics\Semester_4\TA\21st Feb\numpy\data.txt', delimiter = ',')
print(output) #default it float64
print(output.dtype)
output = output.astype('int32')
print(output)
print(output.dtype,'\n')


[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 3.  6.  2.  6.  4.  2.  6.  3.  7.  1.]]
float64
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 3  6  2  6  4  2  6  3  7  1]]
int32 



###### advanced indexing:

In [80]:
# you can index with a list in numpy
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([0,4,7])
print(x[y],'\n')

[1 5 8] 



In [81]:
# Indexing in 2D arrays
adolph = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(adolph,'\n')
print(adolph[1:3, 0:2],'\n') #by default step size = 1
# indexing using list
hitler = adolph[[0,1],[1,2]] # first list for row index, second list for col index
print(hitler,'\n')
print(adolph[[0,2], 1:],'\n') # [0,2] operates on rows, 1: operates on columns


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5]
 [7 8]] 

[2 6] 

[[2 3]
 [8 9]] 



###### boolean masking

In [82]:
print(output>5,'\n') # outputs a list of bool values

[[False False False False False  True  True  True  True  True]
 [False  True False  True False False  True False  True False]] 



In [83]:
# this boolean list then can be used to filter values from original array
refined = output[output>5]
print(refined,'\n')

[ 6  7  8  9 10  6  6  6  7] 



In [85]:
print(output,'\n')
z = np.any(output > 5, axis = 0) # returns true if ANY element is > 5 along one particular column
print(z,'\n')
z = np.all(output > 5, axis = 0) # returns true only if ALL elements are > 5 along one particular column
print(z,'\n')

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 3  6  2  6  4  2  6  3  7  1]] 

[False  True False  True False  True  True  True  True  True] 

[False False False False False False  True False  True False] 



In [87]:
print(((output > 3) & (output < 8)),'\n')
print(((output > 3) | (output < 8)),'\n') 
print((~((output > 3) & (output < 8))),'\n')


[[False False False  True  True  True  True False False False]
 [False  True False  True  True False  True False  True False]] 

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]] 

[[ True  True  True False False False False  True  True  True]
 [ True False  True False False  True False  True False  True]] 



###### saving and loading a numpy array

In [88]:
nzt = np.array([[1,2,3],[6,7,8]])
np.save(r"E:\academics\Semester_4\TA\21st Feb\numpy\nzt.npy", nzt)

In [89]:
nzt_load = np.load(r"E:\academics\Semester_4\TA\21st Feb\numpy\nzt.npy")
print(nzt_load)

[[1 2 3]
 [6 7 8]]


### Assignments:

1. Create a 1x7 Numpy array whose elements consist of a geometric progression with a = 1 & r = 3.

2. Transform each of the element of the below matrix according to the below equation

    if x is an element in input matrix, output matrix should have 
$1/(x^2 + 1)$ in its place

mat = [[1,2,3],[4,5,6]]

3. Make a 5x5 NumPy array of all zeros and use indexing and broadcasting to modify it such that all the elements not on the border are 1

4. using numpy, instantiate 13x13 zeros matrix then modify it to make the below matrix: \\
[[0,0,0,0,0,0,0,0,0,0,0,0,0]
 [0,1,1,1,1,1,1,1,1,1,1,1,0]
 [0,1,2,2,2,2,2,2,2,2,2,1,0]
 [0,1,2,3,3,3,3,3,3,3,2,1,0]
 [0,1,2,3,4,4,4,4,4,3,2,1,0]
 [0,1,2,3,4,5,5,5,4,3,2,1,0]
 [0,1,2,3,4,5,6,5,4,3,2,1,0]
 [0,1,2,3,4,5,5,5,4,3,2,1,0]
 [0,1,2,3,4,4,4,4,4,3,2,1,0]
 [0,1,2,3,3,3,3,3,3,3,2,1,0]
 [0,1,2,2,2,2,2,2,2,2,2,1,0]
 [0,1,1,1,1,1,1,1,1,1,1,1,0]
 [0,0,0,0,0,0,0,0,0,0,0,0,0]
]

5. make a 3 dimensional array of shape 3,3,3 having values 1-27 in sequence
1) Slice this matrix to contain only second and third rows, first and second columns. \\
2) Output a two dimensional matrix as shown below \\
[[0,3,6],[9,12,15],[18,21,14]]

6. Make a 2 dimensional array of size 3,3 having values 1-9 in sequence and modify it such that even values remains unchanged but odd values are changed to zero 

7. Make a 2 dimensional array of size 8,4 having values 1-32 in sequence. use list indexing to output all the even elements in the matrix

8. Make matrix1 as a 2 dimensional array of size 3,3 having value 0-8 in sequence. make matrix2 as a 2 dimensional array of size 3,3 having values 1-9 in sequence. use masking and conditional logic to replace all the odd elements of matrix A with even elements of matrix B

9. solve for x and y using numpy \\
2x + 5y = 20 \\
3x + 6y = 12